#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/turtlebot100/.vscode-server/cli/servers/Stable-61b3d0ab13be7dda2389f1d3e60a119c7f660cc3/server/node" "/home/turtlebot100/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"